spring:
  application:
    name: journalApp

  data:
    mongodb:
      uri: mongodb+srv://<username>:<password@mongocluster.kiyhuzg.mongodb.net/?appName=<cluster-name>
      #host: localhost #for local db integration
      #port: 27017
      database: journalDB
      auto-index-creation: true

    redis:
      host: <redis_host>
      port: <redis_port>
      password: <redis_password>

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: <your_email>
    password: <password> //created using app password for email
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      legion:
        journal: TRACE

weather:
  api:
    key: <api_key>


