spring:
  application:
    name: journalApp

  data:
    mongodb:
      uri: mongodb+srv://<username>:<password@mongocluster.kiyhuzg.mongodb.net/?appName=<cluster-name>
      #host: localhost #for local db integration
      #port: 27017
      database: journalDB
      auto-index-creation: true

    redis:
      host: <redis_host>
      port: <redis_port>
      password: <redis_password>

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: <your_email>
    password: <password> //created using app password for email
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap:
      servers: ${Bootstrap_Server(s)}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: sentiment-group
      properties:
        spring:
          json:
            trusted:
              packages: *
          value:
            default:
              type: com.legion.journal.model.SentimentData
    properties:
      security:
        protocol: PLAINTEXT
      session:
        timeout:
          ms: 45000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${Google_Client_Id}
            client-secret: ${Google_Client_Secret}

  server:
    port: ${Server_Port}
    servlet:
      context-path: /app

logging:
  level:
    com:
      legion:
        journal: TRACE

weather:
  api:
    key: <api_key>


